src/org/dlese/dpc/action/form/SimpleQueryForm.java
/*
	Copyright 2017 Digital Learning Sciences (DLS) at the
	University Corporation for Atmospheric Research (UCAR),
	P.O. Box 3000, Boulder, CO 80307

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package org.dlese.dpc.action.form;

import org.dlese.dpc.action.SimpleQueryAction;
import org.dlese.dpc.index.*;
import org.dlese.dpc.index.reader.*;
import org.dlese.dpc.repository.*;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionServlet;
import org.apache.struts.util.MessageResources;

import javax.servlet.*;
import javax.servlet.http.HttpServletRequest;
import java.util.*;
import java.io.*;
import java.text.*;
import java.net.URLEncoder;

/**
 *  A Struts Form bean for handling query requests that access a {@link
 *  org.dlese.dpc.index.SimpleLuceneIndex}. This class works in conjuction with the {@link
 *  org.dlese.dpc.action.SimpleQueryAction} Struts Action class.
 *
 * @author     John Weatherley
 */
public final class SimpleQueryForm extends ActionForm implements Serializable {
	private static boolean debug = false;
	private int numPagingRecords = 10;
	private int start = -1;
	private HttpServletRequest request;

	private String queryString = null;
	private String refineQueryString = null;
	private XMLDocReader docReader = null;
	private String metadata = null;
	private String reportTitle = null;
	private String selectedCollection = null;
	private String[] selectedCollections = null;
	private String[] selectedFormats = null;
	private String[] selectedSetSpecs = null;
	private List collections = null;
	private List collectionLabels = null;
	private List formats = null;
	private String contextURL = null;
	private ResultDoc resultDoc = null;
	private ResultDocList resultDocs = null;


	/**  Constructor for the SimpleQueryForm object */
	public SimpleQueryForm() { }


	/**
	 *  Gets the contextURL attribute of the SimpleQueryForm object
	 *
	 * @return    The contextURL value
	 */
	public String getContextURL() {
		return contextURL;
	}


	/**
	 *  Sets the contextURL attribute of the SimpleQueryForm object
	 *
	 * @param  contextURL  The new contextURL value
	 */
	public void setContextURL(String contextURL) {
		this.contextURL = contextURL;
	}



	/**
	 *  Sets the collections attribute of the SimpleQueryForm object
	 *
	 * @param  collections  The new collections value
	 */
	public void setCollections(List collections) {
		this.collections = collections;
	}


	/**
	 *  Gets the collections attribute of the SimpleQueryForm object
	 *
	 * @return    The collections value
	 */
	public List getCollections() {
		if (collections == null)
			return new ArrayList();
		return collections;
	}


	/**
	 *  Sets the collectionLabels attribute of the SimpleQueryForm object
	 *
	 * @param  collectionLabels  The new collectionLabels value
	 */
	public void setCollectionLabels(List collectionLabels) {
		prtln("setCollectionLabels() size ");
		this.collectionLabels = collectionLabels;
	}


	/**
	 *  Gets the collectionLabels attribute of the SimpleQueryForm object
	 *
	 * @return    The collectionLabels value
	 */
	public List getCollectionLabels() {
		return collectionLabels;
	}


	/**
	 *  Gets the OAI SetSpecs for this repository, or null if none.
	 *
	 * @return    The OAI SetSpecs
	 */
	public List getOaiSets() {
		RepositoryManager rm =
			(RepositoryManager) getServlet().getServletContext().getAttribute("repositoryManager");
		ArrayList setsList = new ArrayList();
		setsList.add(SimpleQueryAction.SELECT_ALL);
		if (rm == null)
			return setsList;
		String[] sets = rm.getOaiSets();
		if (sets == null)
			return setsList;
		for (int i = 0; i < sets.length; i++)
			setsList.add(sets[i]);
		return setsList;
	}


	/**
	 *  Gets the formats attribute of the SimpleQueryForm object
	 *
	 * @return    The formats value
	 */
	public List getFormats() {
		return formats;
	}



	/**
	 *  Sets the formats attribute of the SimpleQueryForm object
	 *
	 * @param  formats  The new formats value
	 */
	public void setFormats(List formats) {
		prtln("setFormats() size ");
		this.formats = formats;
	}



	/**
	 *  Gets the formatLabels attribute of the SimpleQueryForm object
	 *
	 * @return    The formatLabels value
	 */
	public List getFormatLabels() {
		return getFormats();
	}



	/**
	 *  Gets the status attribute of the SimpleQueryForm object
	 *
	 * @return    The status value
	 */
	public List getStatus() {
		List list = new ArrayList(4);
		list.add(SimpleQueryAction.SELECT_ALL);
		list.add("false");
		list.add("true");
		list.add("deletedNotInDir");
		return list;
	}



	/**
	 *  Gets the statusLabels attribute of the SimpleQueryForm object
	 *
	 * @return    The statusLabels value
	 */
	public List getStatusLabels() {
		List list = new ArrayList(4);
		list.add(SimpleQueryAction.SELECT_ALL);
		list.add("not deleted");
		list.add("deleted");
		list.add("deleted not in any directory");
		return list;
	}


	private String[] selStatus = null;


	/**
	 *  Gets the selStatus attribute of the SimpleQueryForm object
	 *
	 * @return    The selStatus value
	 */
	public String[] getSelStatus() {
		if (selStatus == null)
			selStatus = new String[]{SimpleQueryAction.SELECT_ALL};
		return selStatus;
	}


	/**
	 *  Sets the selStatus attribute of the SimpleQueryForm object
	 *
	 * @param  s  The new selStatus value
	 */
	public void setSelStatus(String[] s) {
		selStatus = s;
	}


	/**
	 *  Gets the sfmts attribute of the SimpleQueryForm object
	 *
	 * @return    The sfmts value
	 */
	public String[] getSfmts() {
		if (selectedFormats == null) {
			selectedFormats = new String[1];
			if (getFormats() == null || getFormats().size() == 0)
				selectedFormats[0] = "";
			else
				selectedFormats[0] = (String) getCollections().get(0);
		}
		return selectedFormats;
	}



	/**
	 *  Sets the sfmts attribute of the SimpleQueryForm object
	 *
	 * @param  selectedFormats  The new sfmts value
	 */
	public void setSfmts(String[] selectedFormats) {
		this.selectedFormats = selectedFormats;
	}



	/**
	 *  Gets the collection that has been selected by the user in the UI via a Select tag. For example '0dcc'.
	 *  For use with a Struts select tag that does not have multiple selection enabled.<p>
	 *
	 *  Sample HTML code using Struts:<br>
	 *  <code><br>
	 *  &lt;html:select property="sc" size="1" &gt;<br>
	 *  &nbsp;&nbsp;&lt;html:options name="queryForm" property="collections"
	 *  labelProperty="collectionLabels"/&gt;<br>
	 *  &lt;/html:select&gt; <br>
	 *
	 *
	 * @return    The selected collection.
	 */
	public String getSc() {
		if (selectedCollection == null) {
			if (getCollections() == null || getCollections().size() == 0)
				return "";
			return (String) getCollections().get(0);
		}
		return selectedCollection;
	}


	/**
	 *  Sets the collection that has been selected by the user in the UI via a Select tag. For example '0dcc'.
	 *  For use with a Struts select tag that does not have multiple selection enabled.
	 *
	 * @param  selectedCollection  The new sc value
	 */
	public void setSc(String selectedCollection) {
		this.selectedCollection = selectedCollection;
	}


	/**
	 *  Gets the OAI SetSpecs that have been selected by the user in the UI. For example 'dcc' 'comet'. For use
	 *  with a Struts select tag that has multiple selection enabled.
	 *
	 * @return    The selected setSpecs
	 */
	public String[] getSelSetSpecs() {
		if (selectedSetSpecs == null) {
			selectedSetSpecs = new String[1];
			List setSpecs = getOaiSets();
			if (setSpecs == null || setSpecs.size() == 0)
				selectedSetSpecs[0] = "";
			else
				selectedSetSpecs[0] = (String) setSpecs.get(0);
		}
		return selectedSetSpecs;
	}


	/**
	 *  Gets the OAI SetSpecs that have been selected by the user in the UI. For example 'dcc' 'comet'. For use
	 *  with a Struts select tag that has multiple selection enabled.
	 *
	 * @param  value  The selected setSpecs
	 */
	public void setSelSetSpecs(String[] value) {
		selectedSetSpecs = value;
	}


	/**
	 *  Gets the collections that have been selected by the user in the UI. For example '0dcc' '0comet'. For use
	 *  with a Struts select tag that has multiple selection enabled.<p>
	 *
	 *  Sample HTML code using Struts:<br>
	 *  <code><br>
	 *  &lt;html:select property="scs" size="5" multiple="t"&gt;<br>
	 *  &nbsp;&nbsp;&lt;html:options name="queryForm" property="collections"
	 *  labelProperty="collectionLabels"/&gt;<br>
	 *  &lt;/html:select&gt; <br>
	 *
	 *
	 * @return    The selected collections.
	 */
	public String[] getScs() {
		if (selectedCollections == null) {
			selectedCollections = new String[1];
			if (getCollections() == null || getCollections().size() == 0)
				selectedCollections[0] = "";
			else
				selectedCollections[0] = (String) getCollections().get(0);
		}
		return selectedCollections;
	}


	/**
	 *  Sets the collection that has been selected by the user in the UI. For example '0dcc' '0comet'. For use
	 *  with a Struts select tag that has multiple selection enabled.
	 *
	 * @param  selectedCollections  The new sc value
	 */
	public void setScs(String[] selectedCollections) {
		this.selectedCollections = selectedCollections;
	}


	/**
	 *  Gets the selected collection(s) parameter to be inserted in the URL that gets the next set of results.
	 *
	 * @return    The scparams value.
	 */

src/org/dlese/dpc/oai/provider/action/OaiPmhSearchAction.java
/*
	Copyright 2017 Digital Learning Sciences (DLS) at the
	University Corporation for Atmospheric Research (UCAR),
	P.O. Box 3000, Boulder, CO 80307

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package org.dlese.dpc.oai.provider.action;

import org.dlese.dpc.oai.provider.action.form.*;
import org.dlese.dpc.repository.*;
import org.dlese.dpc.xml.XMLValidator;
import org.dlese.dpc.webapps.tools.GeneralServletTools;

import java.util.*;
import java.lang.*;
import java.io.*;
import java.util.Hashtable;
import java.util.Locale;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionServlet;
import org.apache.struts.util.MessageResources;

/**
 *  Implementation of <strong>Action</strong> that handles the OAI-PMH search page.
 *
 * @author    John Weatherley
 */
public final class OaiPmhSearchAction extends Action {


	/**
	 *  Process the specified HTTP request, and create the corresponding HTTP response (or
	 *  forward to another web component that will create it). Return an <code>ActionForward</code>
	 *  instance describing where and how control should be forwarded, or <code>null</code>
	 *  if the response has already been completed.
	 *
	 * @param  mapping        The ActionMapping used to select this instance
	 * @param  response       The HTTP response we are creating
	 * @param  form           The ActionForm for the given page
	 * @param  req            DESCRIPTION
	 * @return                The ActionForward instance describing where and how control
	 *      should be forwarded
	 * @exception  Exception  DESCRIPTION
	 */
	public ActionForward execute(
	                             ActionMapping mapping,
	                             ActionForm form,
	                             HttpServletRequest req,
	                             HttpServletResponse response)
		 throws Exception {

		/*
		 *  Design note:
		 *  Only one instance of this class gets created for the app and shared by
		 *  all threads. To be thread-safe, use only local variables, not instance
		 *  variables (the JVM will handle these properly using the stack). Pass
		 *  all variables via method signatures rather than instance vars.
		 */
		// Extract attributes we will need
		
		Locale locale = getLocale(req);
		MessageResources messages = getResources(req);
		
		OaiPmhSearchForm opsf = (OaiPmhSearchForm) form;

		RepositoryManager rm =
			(RepositoryManager) servlet.getServletContext().getAttribute("repositoryManager");
		
		// Set up data for use int the bean.
		opsf.setContextURL(GeneralServletTools.getContextUrl(req));
		opsf.setOaiIdPfx(rm.getOaiIdPrefix());
		opsf.setOaiIdPfx(rm.getOaiIdPrefix());
		opsf.setAvailableSets(rm.getEnabledSets());
		opsf.setExampleId(rm.getExampleID());
		List formats = rm.getAvailableFormatsList();
		opsf.setAvailableFormats(formats);
		if(formats != null && formats.size() > 0)
			opsf.setExampleFormat((String)formats.get(0));
		
		// Add formats list
		// Add sets list
		// Add method in rm to get the BaseURL...

		try {

			// Handle admin actions:
			if (req.getParameter("command") != null) {
				if (req.getParameter("command").equals("Update index")) {

				}
			}

			if (req.getParameter("show") != null) {
				if (req.getParameter("show").equals("odl")) {
					return mapping.findForward("odl.search");
				}
			}						

			return mapping.findForward("oaipmh.search");
		} catch (NullPointerException e) {
			prtln("OaiPmhSearchAction caught null pointer exception.");
			e.printStackTrace();
			return mapping.findForward("oaipmh.search");		
		} catch (Throwable e) {
			prtln("OaiPmhSearchAction caught exception. " + e);
			return mapping.findForward("oaipmh.search");
		}
	}


	/**
	 *  Gets the index associated with a request parameter of the form myParameter[i] where
	 *  the collection index is indicated in brackets.
	 *
	 * @param  paramName  The request parameter String
	 * @return            The index value
	 */
	private final int getIndex(String paramName) {
		return getIntValue(paramName.substring(paramName.indexOf("[") + 1, paramName.indexOf("]")));
	}


	private final int getIntValue(String isInt) {
		try {
			return Integer.parseInt(isInt);
		} catch (Throwable e) {
			return -1;
		}
	}


	/**
	 *  DESCRIPTION
	 *
	 * @param  s  DESCRIPTION
	 */
	private void prtln(String s) {
		System.out.println(s);
	}	
}

web/TagLibIncludes.jsp
<%-- 
	Includes all JSTL and Struts tag libraries, without adding whitespace to the page.
	Source this file using: <%@ include file="TagLibIncludes.jsp" %>
--%><%@ page language="java" %><%@ page isELIgnored="false" 
%><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" 
%><%@ taglib prefix="x" uri="http://java.sun.com/jsp/jstl/xml" 
%><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" 
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" 
%><%@ taglib prefix="sql" uri="http://java.sun.com/jsp/jstl/sql" 
%><%@ taglib prefix="f" uri="http://www.dlese.org/dpc/dds/tags/dleseELFunctions" 
%><%@ taglib prefix="bean" uri="/WEB-INF/tlds/struts-bean.tld"
%><%@ taglib prefix="html" uri="/WEB-INF/tlds/struts-html.tld" 
%><%@ taglib prefix="logic" uri="/WEB-INF/tlds/struts-logic.tld" 
%><%@ taglib prefix="bean-el" uri="/WEB-INF/tlds/struts-bean-el.tld"
%><%@ taglib prefix="html-el" uri="/WEB-INF/tlds/struts-html-el.tld" 
%><%@ taglib prefix="logic-el" uri="/WEB-INF/tlds/struts-logic-el.tld" 
%><%@ taglib prefix="tiles-el" uri="/WEB-INF/tlds/struts-tiles-el.tld" 
%><%@ taglib prefix="dt" uri="/WEB-INF/tlds/datetime.tld"  
%><%@ taglib prefix="resp" uri="/WEB-INF/tlds/response.tld" 
%><%@ taglib prefix="req" uri="/WEB-INF/tlds/request.tld" %>

web/baseUrl.jsp
<c:choose><%-- Implements the same functionality as repositoryManager.getProviderBaseUrl(request)  --%>
	<c:when test="${empty initParam.serverUrl || initParam.serverUrl == '[determine-from-client]'}">
		<c:set var="myBaseUrl">${f:contextUrl(pageContext.request)}/${initParam.dataProviderBaseUrlPathEnding}</c:set>
	</c:when>
	<c:otherwise>
		<c:set var="myBaseUrl">${initParam.serverUrl}${pageContext.request.contextPath}/${initParam.dataProviderBaseUrlPathEnding}</c:set>
	</c:otherwise>
</c:choose>

web/oai_pmh_search.jsp
<%@ include file="TagLibIncludes.jsp" %>

<c:set var="rm" value="${applicationScope.repositoryManager}"/>
<%@ include file="baseUrl.jsp" %>

<html:html>

<c:set var="title" value="Explore the Data Provider"/>

<head>
<title>${title}</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	
<%-- Include style/menu templates --%>
<%@ include file="../../head.jsp" %>
	
<script language="JavaScript">
	var BASE_URL = "${myBaseUrl}";
	var advanced = "off";
	<logic:match name="opsf" property="showAdvanced" value="true">
		advanced = "on";
	</logic:match>		
</script>

</head>

<body onLoad="document.getRecordForm.identifier.focus()">
  <%-- Include style/menu templates --%>
  <c:import url="top.jsp?sec=provider" />

  

<table cellpadding="6" cellspacing="0"> 
  <tr> 
    <td> 
		  
	  <h1>${title}</h1>
	  Submit OAI-PMH requests to the data provider using the forms below 
	  and view or validate the XML responses. 
	  This page assumes familiarity with <a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm">OAI-PMH requests</a>.
	  
	  <br/>
	  <br/>
	  The baseURL for the data provider is: ${myBaseUrl}
	  <br/>
	  <br/>

	  <html:errors/>				
			

	<table>		
		<%-- ListIdentifiers, ListRecords --%>		
		<tr>
			<td colspan=3>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#ListIdentifiers" class="boldlink" title="See description of ListIdentifiers">ListIdentifiers</a>		
				and
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#ListRecords" class="boldlink" title="See description of ListRecords">ListRecords</a>
			</td>
		</tr>
		<tr>
			<td nowrap>
				Choose verb:
			</td>
			<form name="listRecordsIdentifers" action='javascript:mkListRecordsIdentifers("")'>
			<td nowrap colspan=2>
				<select name="verb">
					<option value="ListIdentifiers">ListIdentifiers</option>
					<option value="ListRecords">ListRecords</option>					
				</select>
				&nbsp;Return set:
				<select name="sets">
					<option value=' -- All -- '> -- All -- </option>
					<c:forEach items="${rm.oaiSets}" var="setSpec">
						<option value='${setSpec}'>${setSpec}</option>	
					</c:forEach>
				</select>				
				&nbsp;Format:
				<select name="formats">			
					<logic:iterate name="opsf" property="availableFormats" id="format" >
						<option value='<bean:write name="format"/>'><bean:write name="format"/></option>	
					</logic:iterate>
				</select>
				<input title="View the ListRecords or ListIdentifiers response" type="button" value="view" onClick='mkListRecordsIdentifers("")'>
				<input title="Validate the ListRecords or ListIdentifiers response" type="button" value="validate" onClick='mkListRecordsIdentifers("rt=validate")'>
			</td>		
			<tr>
				<td>&nbsp;</td>
				<td align=right>
					Records modified since:
				</td>
				<td>
					<select name="from">
						<option value='none'> -- No value -- </option>			
						<logic:iterate name="opsf" property="utcDates" id="date" >
							<option value='<bean:write name="date" property="date"/>'><bean:write name="date" property="label"/></option>	
						</logic:iterate>
					</select>
					&nbsp;[ <a href="oaisearch.do">update time</a> ]
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td align=right>
					Records modified before:
				</td>
				<td>
					<select name="until">
						<option value='none'> -- No value -- </option>			
						<logic:iterate name="opsf" property="utcDates" id="date" >
							<option value='<bean:write name="date" property="date"/>'><bean:write name="date" property="label"/></option>	
						</logic:iterate>
					</select>
					&nbsp;[ <a href="oaisearch.do">update time</a> ]
				</td>
			</tr>
			</form>			

		<tr>
			<td colspan=3 height=20>&nbsp;
				
			</td>
		</tr>
		</table>
		
		<%-- GetRecord --%>
		<table>
		<form name="getRecordForm" action='javascript:mkGetRecord("")'>
		<tr>
			<td colspan=3 nowrap>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#GetRecord" title="See description of GetRecord" class="boldlink"><b>GetRecord</b></a>
			</td>
		</tr>
		<tr>
			<td nowrap>
				Enter ID:
			</td>
			<td nowrap colspan=2>
				<input type="text" name="identifier" size="30">
				<input title="View the GetRecord response" type="button" value="view" onClick='mkGetRecord("")'>
				<input title="Validate the GetRecord response" type="button" value="validate" onClick='mkGetRecord("rt=validate")'>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td nowrap colspan=2>			
				Return in format:
				<select name="formats">			
					<logic:iterate name="opsf" property="availableFormats" id="format" >
						<option value='<bean:write name="format"/>'><bean:write name="format"/></option>	
					</logic:iterate>
				</select>
			</td>
		</tr>
		</form>	
		</table>
		
				


		
		<%-- ResumptionToken --%>		
		<table>
		<tr>
			<td colspan=3 height=20>&nbsp;
				
			</td>
		</tr>		
		<tr>
			<td colspan=3>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#FlowControl" class="boldlink" title="See description of flow control and resumptionToken">ResumptionToken</a>
			</td>
		</tr>
		<tr>
			<td nowrap>
				Enter a token:
			</td>
			<form name="resumptionForm" action="javascript:mkResume("")">
			<td colspan=2>
				<input type="text" name="resumptionToken" size="30">
				<select name="verb">
					<option value="ListIdentifiers">ListIdentifiers</option>
					<option value="ListRecords">ListRecords</option>
				</select>
				<input title="Resume and view the ListRecords or ListIdentifiers response" type="button" value="view" onClick="mkResume('')">
				<input title="Resume and validate the ListRecords or ListIdentifiers response" type="button" value="validate" onClick="mkResume('rt=validate')">
			</td>
			</form>	
		</tr>

		<tr>
			<td colspan=3 height=20>&nbsp;
				
			</td>
		</tr>

		<%-- Identify --%>		
		<tr>
			<td colspan=3>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#Identify" class="boldlink" title="See description of Identify">Identify</a>
			</td>
		</tr>
		<tr>
			<form name="Identify" action="">
			<td colspan=3>
				<input title="View the Identify response" type="button" value="view" onClick='window.location = BASE_URL + "?verb=Identify"'>
				<input title="Validate the Identify response" type="button" value="validate" onClick='window.location = BASE_URL + "?verb=Identify&rt=validate"'>
			</td>
			</form>	
		</tr>			
		<tr>
			<td colspan=3 height=20>&nbsp;
				
			</td>
		</tr>		
		
		<%-- ListSets --%>		
		<tr>
			<td colspan=3>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#ListSets" class="boldlink" title="See description of ListSets">ListSets</a>
			</td>
		</tr>
		<tr>
			<form name="ListSets" action="">
			<td colspan=3>
				<input title="View the ListSets response" type="button" value="view" onClick='window.location = BASE_URL + "?verb=ListSets"'>
				<input title="Validate the ListSets response" type="button" value="validate" onClick='window.location = BASE_URL + "?verb=ListSets&rt=validate"'>
			</td>
			</form>	
		</tr>		

		<tr>
			<td colspan=3 height=20>&nbsp;
				
			</td>
		</tr>
		
		<%-- ListMetadataFormats --%>		
		<tr>
			<td colspan=3>
				<a href="http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#ListMetadataFormats" class="boldlink" title="See description of ListMetadataFormats">ListMetadataFormats</a>
			</td>
		</tr>
		<tr>
			<form name="ListMetadataFormats" action="">
			<td colspan=3>
				<input title="View the ListMetadataFormats response" type="button" value="view" onClick='window.location = BASE_URL + "?verb=ListMetadataFormats"'>
				<input title="Validate the ListMetadataFormats response" type="button" value="validate" onClick='window.location = BASE_URL + "?verb=ListMetadataFormats&rt=validate"'>
			</td>
			</form>	
		</tr>				
	</table>
	

		</td>
	</tr>
</table>


	  
<table height="10">
  <tr> 
    <td>&nbsp;</td>
  </tr>
</table>

  <%-- Include style/menu templates --%>
  <%@ include file="../../bottom.jsp" %>
</body>
</html:html>

web/updateFrequency.jsp
<%-- Outputs the index update frequency in a user-readable time. 
Assumes variable rm contains the RepositoryManager --%>
<c:choose>
	<c:when test="${rm.updateFrequency > 60}">
		<fmt:formatNumber value="${rm.updateFrequency/60}" pattern="#"/> 
		hour${rm.updateFrequency/60 >= 2 ? 's' : ''}
		<c:if test="${rm.updateFrequency%60 != 0}">
			and 
			<fmt:formatNumber value="${rm.updateFrequency%60}" pattern="#"/>
			minute${rm.updateFrequency%60 >= 2 ? 's' : ''}
		</c:if>
	</c:when>
	<c:otherwise>
		${rm.updateFrequency} minute${rm.updateFrequency == 1 ? '' : 's'}
	</c:otherwise>
</c:choose>